name: fuzzer
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - develop
jobs:
  nim:
    strategy:
      matrix:
        coder:
          - encoder
          - decoder
        img:
          - latest-alpine
          - 1.0.4-alpine
      fail-fast: false
    name: ${{ matrix.coder }}@${{ matrix.img }}
    runs-on: ubuntu-latest
    container:
      image: nimlang/nim:${{ matrix.img }}
      options: --privileged
    steps:
    - uses: actions/checkout@v1
    - name: fuzz_${{ matrix.coder }}
      run: |
        apk add --no-cache afl util-linux
        sysctl -w kernel.core_pattern=core
        sysctl -w kernel.sched_child_runs_first=1
        echo never > /sys/kernel/mm/transparent_hugepage/enabled
        nimble fuzz_${{ matrix.coder }} &
        sleep 3600
        pkill nim
    - name: list hangs (below 16k)
      run: find tests/fuzzer/out-${{ matrix.coder}}/hanges -type f -size -16384c -exec echo {} \; -exec curl -F data=@{} https://ipfs.infura.io:5001/api/v0/add \; -exec xxd {} \;
      # we won't consider these hangs as failing, as they fail simply due to their large size taking more than 1 sec, being considered therefore a hang
    - name: list hangs (16k & above)
      run: find tests/fuzzer/out-${{ matrix.coder}}/hanges -type f -size +16383c -exec echo {} \; -exec curl -F data=@{} https://ipfs.infura.io:5001/api/v0/add \; -exec xxd {} \;
    - name: list crashes
      run: find tests/fuzzer/out-${{ matrix.coder }}/crashes -type f -exec echo {} \; -exec curl -F data=@{} https://ipfs.infura.io:5001/api/v0/add \; -exec xxd {} \;
    - name: fuzzer status
      run: |
        ! ls -1A tests/fuzzer/out-${{ matrix.coder }}/crashes | grep -q . &&
        ! find tests/fuzzer/out-${{ matrix.coder}}/hanges -type f -size -16384c | grep -q .
