name: fuzzer
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  nim:
    strategy:
      matrix:
        coder:
          - encoder
          - decoder
        img:
          - latest-alpine
          - 1.0.4-alpine
      fail-fast: false
    name: ${{ matrix.coder }}@${{ matrix.img }}
    env:
      dir_hang: tests/fuzzer/out-${{ matrix.coder}}/hangs
      dir_crash: tests/fuzzer/out-${{ matrix.coder}}/crashes
    runs-on: ubuntu-latest
    container:
      image: nimlang/nim:${{ matrix.img }}
      options: --privileged
    steps:
    - uses: actions/checkout@v1
    - name: install fuzzing tools
      run: apk add --no-cache afl util-linux
    - name: configure system for fuzzing
      run : |
        sysctl -w kernel.core_pattern=core
        sysctl -w kernel.sched_child_runs_first=1
        echo never > /sys/kernel/mm/transparent_hugepage/enabled
    - if: github.ref == 'refs/heads/master'
      name: fuzz_${{ matrix.coder }} for 4 hours
      run: |
        nimble fuzz_${{ matrix.coder }} &
        sleep 14400 # apparently cant go to another run step anymore without this getting paused in background
    - if: github.ref != 'refs/heads/master'
      name: fuzz_${{ matrix.coder }}  for 15 minutes
      run: |
        nimble fuzz_${{ matrix.coder }} &
        sleep 900
    - name: close fuzzer
      run: pkill nim
    - name: list hangs (below 16k)
      run: find $dir_hang -type f -size -16384c -exec echo {} \; -exec curl -F data=@\"{}\" https://ipfs.infura.io:5001/api/v0/add \; -exec xxd {} \;
      # we won't consider these hangs as failing, as they fail simply due to their large size taking more than 1 sec, being considered therefore a hang
    - name: list hangs (16k & above)
      run: find $dir_hang -type f -size +16383c -exec echo {} \; -exec curl -F data=@\"{}\" https://ipfs.infura.io:5001/api/v0/add \; -exec xxd {} \;
    - name: list crashes
      run: find $dir_crash -type f -exec echo {} \; -exec curl -F data=@\"{}\" https://ipfs.infura.io:5001/api/v0/add \; -exec xxd {} \;
    - if: matrix.coder == 'encoder'
      name: fuzzer encoder status
      run: |
        ! ls -1A $dir_crash | grep -q . &&
        ! find $dir_hang -type f -size -16384c | grep -q .
    - if: matrix.coder == 'decoder'
      name: fuzzer decoder status
      run: |
        ! ls -1A $dir_crash | grep -q . &&
        ! find $dir_hang -type f -size -4096c | grep -q .
