name: fuzzer
on: push
jobs:
  nim:
    strategy:
      matrix:
        coder:
          - encoder
          - decoder
        img:
          - latest-alpine
          - 1.0.4-alpine
      fail-fast: false
    name: ${{ matrix.coder }}@${{ matrix.img }}
    runs-on: ubuntu-latest
    container:
      image: nimlang/nim:${{ matrix.img }}
      options: --privileged
    steps:
    - uses: actions/checkout@v1
    - name: fuzz_${{ matrix.coder }}
      run: |
        apk add --no-cache afl
        sysctl -w kernel.core_pattern=core
        nimble fuzz_${{ matrix.coder }} &
        sleep 20000
        pkill nim
    - name: list hangs
      run: find tests/fuzzer/out-${{ matrix.coder }}/hangs -type f -exec echo {} \; -exec xxd {} \;
    - name: list crashes
      run: find tests/fuzzer/out-${{ matrix.coder }}/crashes -type f -exec echo {} \; -exec xxd {} \;
    - name: fuzzer status
      run: |
        ! ls -1A tests/fuzzer/out-${{ matrix.coder }}/crashes | grep -q . &&
        ! ls -1A tests/fuzzer/out-${{ matrix.coder }}/hangs | grep -q .
