name: linter
on:
  - push
  - pull_request
jobs:
  nim:
    strategy:
      matrix:
        check:
          - check_src
            # this check does not return error yet...
            # as stdlib fails the lint
            # and does not play well with unittests
          - check_tests
        img:
          - latest-alpine
          - 1.0.4-alpine
      fail-fast: false
    name: ${{ matrix.check }}@${{ matrix.img }}
    runs-on: ubuntu-latest
    container:
      image: nimlang/nim:${{ matrix.img }}
    steps:
    - uses: actions/checkout@v1
    - run: nimble ${{ matrix.check }}

