name: linter
on:
  - push
  - pull_request
jobs:
  check_src:
    name: check_src@${{ matrix.img }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        img:
          - latest-alpine
          - 1.0.4-alpine
      fail-fast: true
    container: nimlang/nim:${{ matrix.img }}
    steps:
    - uses: actions/checkout@v1
    - run: nimble check_src

